default_hparams: mnist_lenet_300_100
batch_size: 60
gpu: '7'
levels: 25
lr: 0.0012
model_name: mnist_lenet_300_100
optimizer_name: adam
replicate: 6
subcommand: lottery_branch
branch_name: max_random
seed: 259
#algorithm: features_frobenius
trials: 10000
property: activation
top: 3
#lth_path: /home/noga/open_lth_data/lottery_262d95790f20ea2d3f35a8c9845560f2/replicate_5
#lth_data: kmnist
#weight_reg_coeff: 1
#init_lr: 0.001
dataset_name: fashionmnist
training_steps: 40ep
pruning_strategy: sparse_global
num_workers: 3
