default_hparams: mnist_lenet_300_100
batch_size: 60
gpu: '6'
levels: 15-25
lr: 0.0012
model_name: mnist_lenet_300_100
optimizer_name: adam
replicate: 5
subcommand: lottery_branch
branch_name: train_init
#property: features_stable_rank
#trials: 10
seed: 101
#lth_dist: true
#path_max_random: lottery_branch_max_random_a34c06230163fb6cdbb809481966b905/properties_features_erank.log
#path_rand_lt: lottery_branch_cross_domain_d878f350dd8bb76fe79e48fa5ba8229c
#path: lottery_branch_max_random_91f517c14e3a743b2a3993d12b8fdc35
#property: features_erank
#cross_lt_path: /home/noga/open_lth_data/lottery_262d95790f20ea2d3f35a8c9845560f2/replicate_5
#cross_data: kmnist
#cross_fake_path: /home/noga/open_lth_data/lottery_08fa5624de98f7f995fce833a4c4487b/replicate_5
#add_rand_data: true
#path_all_trials: /home/noga/open_lth_data/lottery_efa55fed9865fe839a00d27df3a9969b/replicate_5/level_20/lottery_branch_max_random_6280bf44f29a2d812208bd76f07a939e/properties_weight_erank.log
#normalized: true
#erank_path: lottery_branch_max_random_a34c06230163fb6cdbb809481966b905/properties_features_erank.log
#coherence_path: lottery_branch_max_random_6a77658fc8cc7bea2fe3cc1242717394/properties_features_mutual_coherence.log
#frobenius_path: lottery_branch_max_random_91f517c14e3a743b2a3993d12b8fdc35/properties_features_frobenius.log
#min_singular_path: lottery_branch_max_random_ba02ceb15f0dbc608eb2a66d867ff5d0/properties_min_singular.log
#nuclear_path: lottery_branch_max_random_bff9fc06233d708656ec70ad2ee7c845/properties_features_nuclear.log
#stable_rank_path: lottery_branch_max_random_6dd9deb0e87d209da19831d47792b54f/properties_features_stable_rank.log
#batch_average: 10
#trials: 10000
#property: features_frobenius
#no_activation: true
#top: 3
algorithm: erank_norm
weight_reg_coeff: 0.1
features_norm_coeff: 0.1
init_lr: 0.01
steps: 1000
#init_momentum: 0.9
dataset_name: fashionmnist
#training_steps: 100ep
pruning_fraction: 0.2
pruning_layers_to_ignore: fc.weight
apex_fp16: false
batchnorm_frozen: false
batchnorm_init: uniform
blur_factor: null
data_order_seed: null
display_output_location: false
model_init: kaiming_normal
#quiet: true
num_workers: 3