default_hparams: mnist_lenet_300_100
batch_size: 60
gpu: '6'
levels: 10-25
lr: 0.0012
model_name: mnist_lenet_300_100
optimizer_name: adam
replicate: 5
subcommand: lottery_branch
branch_name: cross_domain
lth_path: /home/noga/open_lth_data/lottery_08fa5624de98f7f995fce833a4c4487b/replicate_5/
lth_data: random
#property: features_erank
#trials: 5000
#rand_data: uniform
#seed: 259
dataset_name: kmnist
training_steps: 40ep
pruning_fraction: 0.2
pruning_layers_to_ignore: fc.weight
apex_fp16: false
batchnorm_frozen: false
batchnorm_init: uniform
blur_factor: null
data_order_seed: null
display_output_location: false
model_init: kaiming_normal
num_workers: 2
