default_hparams: mnist_lenet_300_100
batch_size: 60
gpu: '7'
levels: 16-25
lr: 0.0012
model_name: mnist_lenet_300_100
optimizer_name: adam
replicate: 5
subcommand: lottery_branch
branch_name: train_init
algorithm: mutual_coherence
init_lr: 0.1
steps: 5000
#trials: 10000
#top: 3
#rand_data: gaussian
#no_activation: true
dataset_name: fashionmnist
training_steps: 40ep
pruning_fraction: 0.2
pruning_layers_to_ignore: fc.weight
seed: 259
apex_fp16: false
batchnorm_frozen: false
batchnorm_init: uniform
blur_factor: null
data_order_seed: null
display_output_location: false
model_init: kaiming_normal
num_worker: 0
