default_hparams: mnist_lenet_300_100
batch_size: 60
gpu: '6'
levels: 15-25
lr: 0.0012
#model_name: mnist_lenet_300_100
optimizer_name: adam
replicate: 5
subcommand: lottery_branch
branch_name: max_random
seed: 259
trials: 10000
property: features_mutual_coherence
top: 3
#branch_name: property_distribution
#property: features_erank
#trials: 10000
#rand_data: natural
#cross_domain_path: /home/noga/open_lth_data/lottery_262d95790f20ea2d3f35a8c9845560f2/replicate_5
#cross_domain_data: kmnist
#rand_data: gaussian
#no_activation: true
dataset_name: kmnist
#training_steps: 40ep
pruning_fraction: 0.2
pruning_layers_to_ignore: fc.weight
#seed: 259
apex_fp16: false
batchnorm_frozen: false
batchnorm_init: uniform
blur_factor: null
data_order_seed: null
display_output_location: false
model_init: kaiming_normal
num_worker: 2
