default_hparams: cifar_vgg_19
batch_size: 64
gpu: '7'
levels: 25
model_name: cifar_vgg_19
replicate: 5
subcommand: lottery_branch
branch_name: train_init
weight_reg_coeff: -0.0001
steps: 5000
init_lr: 0.01
#trials: 1000
#property: features_erank
seed: 512
#strategy: global
kaiming_balance: true
pruning_fraction: 0.2
num_workers: 4
warmup_steps: 2ep
